import dayjs from 'dayjs';
import { IPatient } from 'app/shared/model/patient.model';
import { IPrescription } from 'app/shared/model/prescription.model';

export interface IConsultation {
  id?: number;
  dateTime?: string | null;
  temperature?: number;
  weight?: number;
  tension?: string;
  glycemie?: string | null;
  comment?: string | null;
  hypothesis?: string;
  exams?: string;
  treatment?: string;
  author?: string | null;
  og?: string | null;
  vd?: string | null;
  eseptum?: string | null;
  ao?: string | null;
  vGDiastole?: string | null;
  ouvertureAo?: string | null;
  vGSystole?: string | null;
  vp?: string | null;
  oGAo?: string | null;
  fRTeicholtz?: string | null;
  eVp?: string | null;
  septumVg?: string | null;
  fETeicholz?: string | null;
  tapse?: string | null;
  paroiPost?: string | null;
  surfaceOg?: string | null;
  surfaceOd?: string | null;
  mesureVd?: string | null;
  fe?: string | null;
  feA2C?: string | null;
  feBiplan?: string | null;
  e?: string | null;
  a?: string | null;
  eA?: string | null;
  td?: string | null;
  triv?: string | null;
  dureeAmIm?: string | null;
  surfaceRegurgitee?: string | null;
  pba?: string | null;
  qr?: string | null;
  vr?: string | null;
  sor?: string | null;
  fr?: string | null;
  vmaxAp?: string | null;
  itv?: string | null;
  gradMax?: string | null;
  gradMoy?: string | null;
  dc?: string | null;
  iAoextension?: string | null;
  venaContracta?: string | null;
  pht?: string | null;
  iTExtension?: string | null;
  gradMaxB?: string | null;
  paps?: string | null;
  ip?: string | null;
  vmax?: string | null;
  gradMaxC?: string | null;
  gradMoyB?: string | null;
  s?: string | null;
  d?: string | null;
  sD?: string | null;
  aA?: string | null;
  dureeAp?: string | null;
  eAA?: string | null;
  aAA?: string | null;
  eAAa?: string | null;
  eEa?: string | null;
  z?: string | null;
  patient?: IPatient | null;
  ordonance?: IPrescription | null;
}

export const defaultValue: Readonly<IConsultation> = {};
