export const examsList = [
  { label: 'Radio', value: 'Radio' },
  { label: 'TDM', value: 'TDM' },
  { label: 'IRM', value: 'IRM' },
  { label: 'Echographie', value: 'Echographie' },
  { label: 'ECG', value: 'ECG' },
  { label: 'NFS', value: 'NFS' },
  { label: 'CRP', value: 'CRP' },
  { label: 'Urémie', value: 'Urémie' },
  { label: 'Créatininémie', value: 'Créatininémie' },
  { label: 'Hémoglobine Glycosylée', value: 'Hémoglobine Glycosylée' },
  { label: 'Fructosamine', value: 'Fructosamine' },
  { label: 'Hyperglycémie provoquée par voie orale', value: 'Hyperglycémie provoquée par voie orale' },
  { label: 'Créatine', value: 'Créatine' },
  { label: "Analyse d'urine", value: 'analyse_d_urine' },
  { label: 'Analyse de lithiase urinaire', value: 'analyse_de_lithiase_urinaire' },
  { label: 'Analyse du liquide synovial', value: 'analyse_du_liquide_synovial' },
  { label: "Bilan d'hémolyse", value: 'bilan_d_hemolyse' },
  { label: 'Bilan ferrique', value: 'bilan_ferrique' },
  { label: 'Bilan hépatique', value: 'bilan_hepatique' },
  { label: 'Cavernosographie', value: 'cavernosographie' },
  { label: 'CKD - EPI', value: 'ckd_epi' },
  { label: 'Décompte des mouvements fœtaux', value: 'decompte_des_mouvements_foetaux' },
  { label: 'Décompte des plaquettes', value: 'decompte_des_plaquettes' },
  { label: 'Dépistage prénatal', value: 'depistage_prenatal' },
  { label: 'Endoscopie', value: 'endoscopie' },
  { label: 'Fer sérique', value: 'fer_serique' },
  { label: 'Ferritine sérique', value: 'ferritine_serique' },
  { label: 'Glucomètre', value: 'glucometre' },
  { label: "Gradient d'albumine sérique et d'ascite", value: 'gradient_d_albumine_serique_et_d_ascite' },
  { label: 'Hystérométrie', value: 'hysterometrie' },
  { label: "Ponction d'ascite", value: 'ponction_d_ascite' },
  { label: 'Ponction pleurale', value: 'ponction_pleurale' },
  { label: 'Profil bio-physique', value: 'profil_bio_physique' },
  { label: 'QT corrigé', value: 'qt_corrige' },
  { label: 'Radiographie abdominale', value: 'radiographie_abdominale' },
  { label: 'Rapport albumine sur créatinine urinaire', value: 'rapport_albumine_sur_creatinine_urinaire' },
  { label: 'Saturation de la transferrine', value: 'saturation_de_la_transferrine' },
  { label: 'Saturométrie au doigt', value: 'saturometrie_au_doigt' },
  { label: 'Spirométrie', value: 'spirometrie' },
  { label: "Test d'apnée", value: 'test_d_apnee' },
  { label: 'Test de la tumescence pénienne nocturne', value: 'test_de_la_tumescence_penienne_nocturne' },
  { label: 'Total iron binding capacity', value: 'total_iron_binding_capacity' },
  { label: 'Tracé de la réactivité fœtale', value: 'trace_de_la_reactivite_foetale' },
  { label: 'Échographie ciblée de la veine cave inférieure', value: 'echographie_ciblee_de_la_veine_cave_inferieure' },
  {
    label: 'Échographie doppler du pénis avec injection de prostaglandine E1',
    value: 'echographie_doppler_du_penis_avec_injection_de_prostaglandine_e1',
  },
  { label: 'Échographie pénienne', value: 'echographie_penienne' },
];
